/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1sistemasop;

/**
 *
 * @author Personal
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelProduccion = new javax.swing.JPanel();
        productorBrazoPanel = new javax.swing.JPanel();
        productorBrazoLabel = new javax.swing.JLabel();
        botonBrazoC = new javax.swing.JButton();
        botonBrazoD = new javax.swing.JButton();
        progressBarBrazo = new javax.swing.JProgressBar();
        botonProducirBrazo = new javax.swing.JButton();
        cantidadEmpleadosBrazo = new javax.swing.JTextField();
        maxEmpleadosBrazo = new javax.swing.JLabel();
        productorPiernasPanel = new javax.swing.JPanel();
        productorBrazoLabel1 = new javax.swing.JLabel();
        botonBrazoC1 = new javax.swing.JButton();
        botonBrazoD1 = new javax.swing.JButton();
        progressBarBrazo1 = new javax.swing.JProgressBar();
        botonProducirBrazo1 = new javax.swing.JButton();
        cantidadEmpleadosBrazo1 = new javax.swing.JTextField();
        maxEmpleadosBrazo1 = new javax.swing.JLabel();
        productorPiernasPanel1 = new javax.swing.JPanel();
        productorBrazoLabel2 = new javax.swing.JLabel();
        botonBrazoC2 = new javax.swing.JButton();
        botonBrazoD2 = new javax.swing.JButton();
        progressBarBrazo2 = new javax.swing.JProgressBar();
        botonProducirBrazo2 = new javax.swing.JButton();
        cantidadEmpleadosBrazo2 = new javax.swing.JTextField();
        maxEmpleadosBrazo2 = new javax.swing.JLabel();
        productorPiernasPanel2 = new javax.swing.JPanel();
        productorBrazoLabel3 = new javax.swing.JLabel();
        botonBrazoC3 = new javax.swing.JButton();
        botonBrazoD3 = new javax.swing.JButton();
        progressBarBrazo3 = new javax.swing.JProgressBar();
        botonProducirBrazo3 = new javax.swing.JButton();
        cantidadEmpleadosBrazo3 = new javax.swing.JTextField();
        maxEmpleadosBrazo3 = new javax.swing.JLabel();
        panelAlmacen = new javax.swing.JPanel();
        almacenBrazoPanel = new javax.swing.JPanel();
        almacenBrazoLabel = new javax.swing.JLabel();
        progressBarAlmacenBrazo = new javax.swing.JProgressBar();
        cantidadAlmacenBrazo = new javax.swing.JTextField();
        maxAlmacenBrazo = new javax.swing.JLabel();
        almacenBotonPanel = new javax.swing.JPanel();
        almacenBotonLabel = new javax.swing.JLabel();
        progressBarAlmacenBoton = new javax.swing.JProgressBar();
        cantidadAlmacenBoton = new javax.swing.JTextField();
        maxAlmacenBoton = new javax.swing.JLabel();
        almacenPiernaPanel = new javax.swing.JPanel();
        almacenPiernaLabel = new javax.swing.JLabel();
        progressBarAlmacenPierna = new javax.swing.JProgressBar();
        cantidadAlmacenPierna = new javax.swing.JTextField();
        maxAlmacenPierna = new javax.swing.JLabel();
        almacenCuerpoPanel = new javax.swing.JPanel();
        almacenBrazoLabel3 = new javax.swing.JLabel();
        progressBarAlmacenCuerpo3 = new javax.swing.JProgressBar();
        cantidadAlmacenCuerpo = new javax.swing.JTextField();
        maxAlmacenCuerpo = new javax.swing.JLabel();
        panelProduccion1 = new javax.swing.JPanel();
        ensamblajePanaPanel = new javax.swing.JPanel();
        ensambladorPanasLabel = new javax.swing.JLabel();
        botonPanaC = new javax.swing.JButton();
        botonPanaD = new javax.swing.JButton();
        progressBarPana4 = new javax.swing.JProgressBar();
        botonEnsamblarPana = new javax.swing.JButton();
        cantidadEmpleadosPana = new javax.swing.JTextField();
        maxEmpleadosPana = new javax.swing.JLabel();
        almacenBrazoPanel4 = new javax.swing.JPanel();
        almacenPanaLabel = new javax.swing.JLabel();
        cantidadAlmacenPana = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(0, 0, 0));

        panelProduccion.setBackground(new java.awt.Color(255, 51, 51));
        panelProduccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Producción", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 3, 12))); // NOI18N

        productorBrazoPanel.setBackground(new java.awt.Color(204, 204, 204));

        productorBrazoLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        productorBrazoLabel.setText("Productor de brazos");

        botonBrazoC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoC.setText("Contratar");
        botonBrazoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBrazoCActionPerformed(evt);
            }
        });

        botonBrazoD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoD.setText("Despedir");

        progressBarBrazo.setMaximum(5);
        progressBarBrazo.setValue(3);

        botonProducirBrazo.setBackground(new java.awt.Color(255, 255, 255));
        botonProducirBrazo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonProducirBrazo.setText("Producir");
        botonProducirBrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProducirBrazoActionPerformed(evt);
            }
        });

        cantidadEmpleadosBrazo.setEditable(false);
        cantidadEmpleadosBrazo.setText("0");
        cantidadEmpleadosBrazo.setPreferredSize(new java.awt.Dimension(14, 20));
        cantidadEmpleadosBrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadEmpleadosBrazoActionPerformed(evt);
            }
        });

        maxEmpleadosBrazo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxEmpleadosBrazo.setText("/5");

        javax.swing.GroupLayout productorBrazoPanelLayout = new javax.swing.GroupLayout(productorBrazoPanel);
        productorBrazoPanel.setLayout(productorBrazoPanelLayout);
        productorBrazoPanelLayout.setHorizontalGroup(
            productorBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorBrazoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorBrazoPanelLayout.createSequentialGroup()
                        .addComponent(botonBrazoC)
                        .addGap(10, 10, 10)
                        .addComponent(botonBrazoD)
                        .addGap(40, 40, 40)
                        .addComponent(progressBarBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadEmpleadosBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxEmpleadosBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productorBrazoPanelLayout.createSequentialGroup()
                        .addComponent(productorBrazoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonProducirBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productorBrazoPanelLayout.setVerticalGroup(
            productorBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorBrazoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productorBrazoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonProducirBrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(productorBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonBrazoD)
                        .addComponent(botonBrazoC))
                    .addComponent(progressBarBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(productorBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadEmpleadosBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxEmpleadosBrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productorPiernasPanel.setBackground(new java.awt.Color(204, 204, 204));

        productorBrazoLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        productorBrazoLabel1.setText("Productor de piernas");

        botonBrazoC1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoC1.setText("Contratar");
        botonBrazoC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBrazoC1ActionPerformed(evt);
            }
        });

        botonBrazoD1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoD1.setText("Despedir");

        progressBarBrazo1.setMaximum(5);
        progressBarBrazo1.setValue(3);

        botonProducirBrazo1.setBackground(new java.awt.Color(255, 255, 255));
        botonProducirBrazo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonProducirBrazo1.setText("Producir");
        botonProducirBrazo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProducirBrazo1ActionPerformed(evt);
            }
        });

        cantidadEmpleadosBrazo1.setEditable(false);
        cantidadEmpleadosBrazo1.setText("0");
        cantidadEmpleadosBrazo1.setMinimumSize(new java.awt.Dimension(7, 25));
        cantidadEmpleadosBrazo1.setPreferredSize(new java.awt.Dimension(13, 21));
        cantidadEmpleadosBrazo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadEmpleadosBrazo1ActionPerformed(evt);
            }
        });

        maxEmpleadosBrazo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxEmpleadosBrazo1.setText("/4");

        javax.swing.GroupLayout productorPiernasPanelLayout = new javax.swing.GroupLayout(productorPiernasPanel);
        productorPiernasPanel.setLayout(productorPiernasPanelLayout);
        productorPiernasPanelLayout.setHorizontalGroup(
            productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorPiernasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorPiernasPanelLayout.createSequentialGroup()
                        .addComponent(botonBrazoC1)
                        .addGap(10, 10, 10)
                        .addComponent(botonBrazoD1)
                        .addGap(40, 40, 40)
                        .addComponent(progressBarBrazo1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadEmpleadosBrazo1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxEmpleadosBrazo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productorPiernasPanelLayout.createSequentialGroup()
                        .addComponent(productorBrazoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonProducirBrazo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productorPiernasPanelLayout.setVerticalGroup(
            productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorPiernasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productorBrazoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonProducirBrazo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorPiernasPanelLayout.createSequentialGroup()
                        .addGroup(productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonBrazoD1)
                                .addComponent(botonBrazoC1))
                            .addGroup(productorPiernasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidadEmpleadosBrazo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maxEmpleadosBrazo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productorPiernasPanelLayout.createSequentialGroup()
                        .addComponent(progressBarBrazo1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        productorPiernasPanel1.setBackground(new java.awt.Color(204, 204, 204));

        productorBrazoLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        productorBrazoLabel2.setText("Productor de botones");

        botonBrazoC2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoC2.setText("Contratar");
        botonBrazoC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBrazoC2ActionPerformed(evt);
            }
        });

        botonBrazoD2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoD2.setText("Despedir");

        progressBarBrazo2.setMaximum(5);
        progressBarBrazo2.setValue(3);

        botonProducirBrazo2.setBackground(new java.awt.Color(255, 255, 255));
        botonProducirBrazo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonProducirBrazo2.setText("Producir");
        botonProducirBrazo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProducirBrazo2ActionPerformed(evt);
            }
        });

        cantidadEmpleadosBrazo2.setEditable(false);
        cantidadEmpleadosBrazo2.setText("0");
        cantidadEmpleadosBrazo2.setMinimumSize(new java.awt.Dimension(7, 25));
        cantidadEmpleadosBrazo2.setPreferredSize(new java.awt.Dimension(13, 21));
        cantidadEmpleadosBrazo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadEmpleadosBrazo2ActionPerformed(evt);
            }
        });

        maxEmpleadosBrazo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxEmpleadosBrazo2.setText("/4");

        javax.swing.GroupLayout productorPiernasPanel1Layout = new javax.swing.GroupLayout(productorPiernasPanel1);
        productorPiernasPanel1.setLayout(productorPiernasPanel1Layout);
        productorPiernasPanel1Layout.setHorizontalGroup(
            productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorPiernasPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorPiernasPanel1Layout.createSequentialGroup()
                        .addComponent(botonBrazoC2)
                        .addGap(10, 10, 10)
                        .addComponent(botonBrazoD2)
                        .addGap(40, 40, 40)
                        .addComponent(progressBarBrazo2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadEmpleadosBrazo2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxEmpleadosBrazo2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productorPiernasPanel1Layout.createSequentialGroup()
                        .addComponent(productorBrazoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonProducirBrazo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productorPiernasPanel1Layout.setVerticalGroup(
            productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorPiernasPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productorBrazoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonProducirBrazo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorPiernasPanel1Layout.createSequentialGroup()
                        .addGroup(productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonBrazoD2)
                                .addComponent(botonBrazoC2))
                            .addGroup(productorPiernasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidadEmpleadosBrazo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maxEmpleadosBrazo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productorPiernasPanel1Layout.createSequentialGroup()
                        .addComponent(progressBarBrazo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        productorPiernasPanel2.setBackground(new java.awt.Color(204, 204, 204));

        productorBrazoLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        productorBrazoLabel3.setText("Productor de cuerpo");

        botonBrazoC3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoC3.setText("Contratar");
        botonBrazoC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBrazoC3ActionPerformed(evt);
            }
        });

        botonBrazoD3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBrazoD3.setText("Despedir");

        progressBarBrazo3.setMaximum(5);
        progressBarBrazo3.setValue(3);

        botonProducirBrazo3.setBackground(new java.awt.Color(255, 255, 255));
        botonProducirBrazo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonProducirBrazo3.setText("Producir");
        botonProducirBrazo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProducirBrazo3ActionPerformed(evt);
            }
        });

        cantidadEmpleadosBrazo3.setEditable(false);
        cantidadEmpleadosBrazo3.setText("0");
        cantidadEmpleadosBrazo3.setMinimumSize(new java.awt.Dimension(7, 25));
        cantidadEmpleadosBrazo3.setPreferredSize(new java.awt.Dimension(13, 21));
        cantidadEmpleadosBrazo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadEmpleadosBrazo3ActionPerformed(evt);
            }
        });

        maxEmpleadosBrazo3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxEmpleadosBrazo3.setText("/4");

        javax.swing.GroupLayout productorPiernasPanel2Layout = new javax.swing.GroupLayout(productorPiernasPanel2);
        productorPiernasPanel2.setLayout(productorPiernasPanel2Layout);
        productorPiernasPanel2Layout.setHorizontalGroup(
            productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorPiernasPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorPiernasPanel2Layout.createSequentialGroup()
                        .addComponent(botonBrazoC3)
                        .addGap(10, 10, 10)
                        .addComponent(botonBrazoD3)
                        .addGap(40, 40, 40)
                        .addComponent(progressBarBrazo3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadEmpleadosBrazo3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxEmpleadosBrazo3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productorPiernasPanel2Layout.createSequentialGroup()
                        .addComponent(productorBrazoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonProducirBrazo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productorPiernasPanel2Layout.setVerticalGroup(
            productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productorPiernasPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productorBrazoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonProducirBrazo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productorPiernasPanel2Layout.createSequentialGroup()
                        .addGroup(productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonBrazoD3)
                                .addComponent(botonBrazoC3))
                            .addGroup(productorPiernasPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidadEmpleadosBrazo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maxEmpleadosBrazo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productorPiernasPanel2Layout.createSequentialGroup()
                        .addComponent(progressBarBrazo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout panelProduccionLayout = new javax.swing.GroupLayout(panelProduccion);
        panelProduccion.setLayout(panelProduccionLayout);
        panelProduccionLayout.setHorizontalGroup(
            panelProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productorBrazoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productorPiernasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productorPiernasPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productorPiernasPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProduccionLayout.setVerticalGroup(
            panelProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productorBrazoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productorPiernasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productorPiernasPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productorPiernasPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAlmacen.setBackground(new java.awt.Color(255, 51, 51));
        panelAlmacen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Almacen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 0, 12))); // NOI18N

        almacenBrazoPanel.setBackground(new java.awt.Color(204, 204, 204));

        almacenBrazoLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        almacenBrazoLabel.setText("brazos");

        progressBarAlmacenBrazo.setMaximum(5);
        progressBarAlmacenBrazo.setValue(3);

        cantidadAlmacenBrazo.setEditable(false);
        cantidadAlmacenBrazo.setText("0");
        cantidadAlmacenBrazo.setPreferredSize(new java.awt.Dimension(14, 20));
        cantidadAlmacenBrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAlmacenBrazoActionPerformed(evt);
            }
        });

        maxAlmacenBrazo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxAlmacenBrazo.setText("/40");

        javax.swing.GroupLayout almacenBrazoPanelLayout = new javax.swing.GroupLayout(almacenBrazoPanel);
        almacenBrazoPanel.setLayout(almacenBrazoPanelLayout);
        almacenBrazoPanelLayout.setHorizontalGroup(
            almacenBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenBrazoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenBrazoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(progressBarAlmacenBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(almacenBrazoPanelLayout.createSequentialGroup()
                        .addComponent(almacenBrazoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadAlmacenBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxAlmacenBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        almacenBrazoPanelLayout.setVerticalGroup(
            almacenBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenBrazoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenBrazoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadAlmacenBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxAlmacenBrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(almacenBrazoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBarAlmacenBrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        almacenBotonPanel.setBackground(new java.awt.Color(204, 204, 204));

        almacenBotonLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        almacenBotonLabel.setText("botones");

        progressBarAlmacenBoton.setMaximum(5);
        progressBarAlmacenBoton.setValue(3);

        cantidadAlmacenBoton.setEditable(false);
        cantidadAlmacenBoton.setText("0");
        cantidadAlmacenBoton.setPreferredSize(new java.awt.Dimension(14, 20));
        cantidadAlmacenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAlmacenBotonActionPerformed(evt);
            }
        });

        maxAlmacenBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxAlmacenBoton.setText("/40");

        javax.swing.GroupLayout almacenBotonPanelLayout = new javax.swing.GroupLayout(almacenBotonPanel);
        almacenBotonPanel.setLayout(almacenBotonPanelLayout);
        almacenBotonPanelLayout.setHorizontalGroup(
            almacenBotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenBotonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenBotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenBotonPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(progressBarAlmacenBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(almacenBotonPanelLayout.createSequentialGroup()
                        .addComponent(almacenBotonLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadAlmacenBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxAlmacenBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        almacenBotonPanelLayout.setVerticalGroup(
            almacenBotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenBotonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenBotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenBotonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadAlmacenBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxAlmacenBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(almacenBotonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBarAlmacenBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        almacenPiernaPanel.setBackground(new java.awt.Color(204, 204, 204));

        almacenPiernaLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        almacenPiernaLabel.setText("Piernas");

        progressBarAlmacenPierna.setMaximum(5);
        progressBarAlmacenPierna.setValue(3);

        cantidadAlmacenPierna.setEditable(false);
        cantidadAlmacenPierna.setText("0");
        cantidadAlmacenPierna.setPreferredSize(new java.awt.Dimension(14, 20));
        cantidadAlmacenPierna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAlmacenPiernaActionPerformed(evt);
            }
        });

        maxAlmacenPierna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxAlmacenPierna.setText("/40");

        javax.swing.GroupLayout almacenPiernaPanelLayout = new javax.swing.GroupLayout(almacenPiernaPanel);
        almacenPiernaPanel.setLayout(almacenPiernaPanelLayout);
        almacenPiernaPanelLayout.setHorizontalGroup(
            almacenPiernaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenPiernaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenPiernaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenPiernaPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(progressBarAlmacenPierna, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(almacenPiernaPanelLayout.createSequentialGroup()
                        .addComponent(almacenPiernaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadAlmacenPierna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxAlmacenPierna, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        almacenPiernaPanelLayout.setVerticalGroup(
            almacenPiernaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenPiernaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenPiernaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenPiernaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadAlmacenPierna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxAlmacenPierna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(almacenPiernaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBarAlmacenPierna, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        almacenCuerpoPanel.setBackground(new java.awt.Color(204, 204, 204));

        almacenBrazoLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        almacenBrazoLabel3.setText("cuerpos");

        progressBarAlmacenCuerpo3.setMaximum(5);
        progressBarAlmacenCuerpo3.setValue(3);

        cantidadAlmacenCuerpo.setEditable(false);
        cantidadAlmacenCuerpo.setText("0");
        cantidadAlmacenCuerpo.setPreferredSize(new java.awt.Dimension(14, 20));
        cantidadAlmacenCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAlmacenCuerpoActionPerformed(evt);
            }
        });

        maxAlmacenCuerpo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxAlmacenCuerpo.setText("/40");

        javax.swing.GroupLayout almacenCuerpoPanelLayout = new javax.swing.GroupLayout(almacenCuerpoPanel);
        almacenCuerpoPanel.setLayout(almacenCuerpoPanelLayout);
        almacenCuerpoPanelLayout.setHorizontalGroup(
            almacenCuerpoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenCuerpoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenCuerpoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenCuerpoPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(progressBarAlmacenCuerpo3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(almacenCuerpoPanelLayout.createSequentialGroup()
                        .addComponent(almacenBrazoLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadAlmacenCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxAlmacenCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        almacenCuerpoPanelLayout.setVerticalGroup(
            almacenCuerpoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenCuerpoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenCuerpoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(almacenCuerpoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadAlmacenCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxAlmacenCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(almacenBrazoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBarAlmacenCuerpo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAlmacenLayout = new javax.swing.GroupLayout(panelAlmacen);
        panelAlmacen.setLayout(panelAlmacenLayout);
        panelAlmacenLayout.setHorizontalGroup(
            panelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(almacenBrazoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(almacenPiernaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(almacenBotonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(almacenCuerpoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlmacenLayout.setVerticalGroup(
            panelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(almacenBrazoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(almacenBotonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(almacenCuerpoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(almacenPiernaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProduccion1.setBackground(new java.awt.Color(255, 51, 51));
        panelProduccion1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ensamblaje", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 0, 12))); // NOI18N

        ensamblajePanaPanel.setBackground(new java.awt.Color(204, 204, 204));

        ensambladorPanasLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        ensambladorPanasLabel.setText("ensamblador de panas");

        botonPanaC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonPanaC.setText("Contratar");
        botonPanaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPanaCActionPerformed(evt);
            }
        });

        botonPanaD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonPanaD.setText("Despedir");

        progressBarPana4.setMaximum(5);
        progressBarPana4.setValue(3);

        botonEnsamblarPana.setBackground(new java.awt.Color(255, 255, 255));
        botonEnsamblarPana.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonEnsamblarPana.setText("Ensamblar");
        botonEnsamblarPana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnsamblarPanaActionPerformed(evt);
            }
        });

        cantidadEmpleadosPana.setEditable(false);
        cantidadEmpleadosPana.setText("0");
        cantidadEmpleadosPana.setPreferredSize(new java.awt.Dimension(14, 20));
        cantidadEmpleadosPana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadEmpleadosPanaActionPerformed(evt);
            }
        });

        maxEmpleadosPana.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maxEmpleadosPana.setText("/5");

        javax.swing.GroupLayout ensamblajePanaPanelLayout = new javax.swing.GroupLayout(ensamblajePanaPanel);
        ensamblajePanaPanel.setLayout(ensamblajePanaPanelLayout);
        ensamblajePanaPanelLayout.setHorizontalGroup(
            ensamblajePanaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ensamblajePanaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ensamblajePanaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ensamblajePanaPanelLayout.createSequentialGroup()
                        .addComponent(botonPanaC)
                        .addGap(10, 10, 10)
                        .addComponent(botonPanaD)
                        .addGap(40, 40, 40)
                        .addComponent(progressBarPana4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadEmpleadosPana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxEmpleadosPana, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ensamblajePanaPanelLayout.createSequentialGroup()
                        .addComponent(ensambladorPanasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEnsamblarPana, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ensamblajePanaPanelLayout.setVerticalGroup(
            ensamblajePanaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ensamblajePanaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ensamblajePanaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ensambladorPanasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnsamblarPana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(ensamblajePanaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ensamblajePanaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonPanaD)
                        .addComponent(botonPanaC))
                    .addComponent(progressBarPana4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ensamblajePanaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidadEmpleadosPana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxEmpleadosPana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        almacenBrazoPanel4.setBackground(new java.awt.Color(204, 204, 204));

        almacenPanaLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        almacenPanaLabel.setText("Panas");

        cantidadAlmacenPana.setEditable(false);
        cantidadAlmacenPana.setText("0");
        cantidadAlmacenPana.setPreferredSize(new java.awt.Dimension(14, 20));
        cantidadAlmacenPana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAlmacenPanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout almacenBrazoPanel4Layout = new javax.swing.GroupLayout(almacenBrazoPanel4);
        almacenBrazoPanel4.setLayout(almacenBrazoPanel4Layout);
        almacenBrazoPanel4Layout.setHorizontalGroup(
            almacenBrazoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenBrazoPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(almacenPanaLabel)
                .addGap(18, 18, 18)
                .addComponent(cantidadAlmacenPana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        almacenBrazoPanel4Layout.setVerticalGroup(
            almacenBrazoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(almacenBrazoPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(almacenBrazoPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadAlmacenPana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(almacenPanaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelProduccion1Layout = new javax.swing.GroupLayout(panelProduccion1);
        panelProduccion1.setLayout(panelProduccion1Layout);
        panelProduccion1Layout.setHorizontalGroup(
            panelProduccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduccion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProduccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ensamblajePanaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(almacenBrazoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelProduccion1Layout.setVerticalGroup(
            panelProduccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProduccion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ensamblajePanaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(almacenBrazoPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProduccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelProduccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBrazoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBrazoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBrazoCActionPerformed

    private void botonProducirBrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProducirBrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProducirBrazoActionPerformed

    private void cantidadEmpleadosBrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadEmpleadosBrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadEmpleadosBrazoActionPerformed

    private void botonBrazoC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBrazoC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBrazoC1ActionPerformed

    private void botonProducirBrazo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProducirBrazo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProducirBrazo1ActionPerformed

    private void cantidadEmpleadosBrazo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadEmpleadosBrazo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadEmpleadosBrazo1ActionPerformed

    private void botonBrazoC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBrazoC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBrazoC2ActionPerformed

    private void botonProducirBrazo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProducirBrazo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProducirBrazo2ActionPerformed

    private void cantidadEmpleadosBrazo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadEmpleadosBrazo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadEmpleadosBrazo2ActionPerformed

    private void botonBrazoC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBrazoC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBrazoC3ActionPerformed

    private void botonProducirBrazo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProducirBrazo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProducirBrazo3ActionPerformed

    private void cantidadEmpleadosBrazo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadEmpleadosBrazo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadEmpleadosBrazo3ActionPerformed

    private void cantidadAlmacenBrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAlmacenBrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAlmacenBrazoActionPerformed

    private void cantidadAlmacenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAlmacenBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAlmacenBotonActionPerformed

    private void cantidadAlmacenPiernaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAlmacenPiernaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAlmacenPiernaActionPerformed

    private void cantidadAlmacenCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAlmacenCuerpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAlmacenCuerpoActionPerformed

    private void botonPanaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPanaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPanaCActionPerformed

    private void botonEnsamblarPanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnsamblarPanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnsamblarPanaActionPerformed

    private void cantidadEmpleadosPanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadEmpleadosPanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadEmpleadosPanaActionPerformed

    private void cantidadAlmacenPanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAlmacenPanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAlmacenPanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel almacenBotonLabel;
    private javax.swing.JPanel almacenBotonPanel;
    private javax.swing.JLabel almacenBrazoLabel;
    private javax.swing.JLabel almacenBrazoLabel3;
    private javax.swing.JPanel almacenBrazoPanel;
    private javax.swing.JPanel almacenBrazoPanel4;
    private javax.swing.JPanel almacenCuerpoPanel;
    private javax.swing.JLabel almacenPanaLabel;
    private javax.swing.JLabel almacenPiernaLabel;
    private javax.swing.JPanel almacenPiernaPanel;
    private javax.swing.JButton botonBrazoC;
    private javax.swing.JButton botonBrazoC1;
    private javax.swing.JButton botonBrazoC2;
    private javax.swing.JButton botonBrazoC3;
    private javax.swing.JButton botonBrazoD;
    private javax.swing.JButton botonBrazoD1;
    private javax.swing.JButton botonBrazoD2;
    private javax.swing.JButton botonBrazoD3;
    private javax.swing.JButton botonEnsamblarPana;
    private javax.swing.JButton botonPanaC;
    private javax.swing.JButton botonPanaD;
    private javax.swing.JButton botonProducirBrazo;
    private javax.swing.JButton botonProducirBrazo1;
    private javax.swing.JButton botonProducirBrazo2;
    private javax.swing.JButton botonProducirBrazo3;
    private javax.swing.JTextField cantidadAlmacenBoton;
    private javax.swing.JTextField cantidadAlmacenBrazo;
    private javax.swing.JTextField cantidadAlmacenCuerpo;
    private javax.swing.JTextField cantidadAlmacenPana;
    private javax.swing.JTextField cantidadAlmacenPierna;
    private javax.swing.JTextField cantidadEmpleadosBrazo;
    private javax.swing.JTextField cantidadEmpleadosBrazo1;
    private javax.swing.JTextField cantidadEmpleadosBrazo2;
    private javax.swing.JTextField cantidadEmpleadosBrazo3;
    private javax.swing.JTextField cantidadEmpleadosPana;
    private javax.swing.JLabel ensambladorPanasLabel;
    private javax.swing.JPanel ensamblajePanaPanel;
    private javax.swing.JLabel maxAlmacenBoton;
    private javax.swing.JLabel maxAlmacenBrazo;
    private javax.swing.JLabel maxAlmacenCuerpo;
    private javax.swing.JLabel maxAlmacenPierna;
    private javax.swing.JLabel maxEmpleadosBrazo;
    private javax.swing.JLabel maxEmpleadosBrazo1;
    private javax.swing.JLabel maxEmpleadosBrazo2;
    private javax.swing.JLabel maxEmpleadosBrazo3;
    private javax.swing.JLabel maxEmpleadosPana;
    private javax.swing.JPanel panelAlmacen;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelProduccion;
    private javax.swing.JPanel panelProduccion1;
    private javax.swing.JLabel productorBrazoLabel;
    private javax.swing.JLabel productorBrazoLabel1;
    private javax.swing.JLabel productorBrazoLabel2;
    private javax.swing.JLabel productorBrazoLabel3;
    private javax.swing.JPanel productorBrazoPanel;
    private javax.swing.JPanel productorPiernasPanel;
    private javax.swing.JPanel productorPiernasPanel1;
    private javax.swing.JPanel productorPiernasPanel2;
    private javax.swing.JProgressBar progressBarAlmacenBoton;
    private javax.swing.JProgressBar progressBarAlmacenBrazo;
    private javax.swing.JProgressBar progressBarAlmacenCuerpo3;
    private javax.swing.JProgressBar progressBarAlmacenPierna;
    private javax.swing.JProgressBar progressBarBrazo;
    private javax.swing.JProgressBar progressBarBrazo1;
    private javax.swing.JProgressBar progressBarBrazo2;
    private javax.swing.JProgressBar progressBarBrazo3;
    private javax.swing.JProgressBar progressBarPana4;
    // End of variables declaration//GEN-END:variables
}
